[package]
name = "stacks-node"
version = "0.1.0"
authors = ["Ludo Galabru <ludovic@blockstack.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
pico-args = "0.3.1"
rand = "=0.7.2"
serde = "1"
serde_derive = "1"
serde_json = { version = "1.0", features = ["arbitrary_precision", "raw_value"] }
stacks = { package = "blockstack-core", path = "../../." }
stx_genesis = { package = "stx-genesis", path = "../../stx-genesis/."}
toml = "0.5.6"
async-h1 = "=1.0"
async-std = { version = "<1.6", features = ["attributes"] }
http-types = "1.0"
base64 = "0.12.0"
backtrace = "0.3.50"
libc = "0.2"
slog = { version = "2.5.2", features = [ "max_level_trace" ] }
ctrlc = { version = "3.1.7", features = [ "termination" ] }

[dev-dependencies]
ring = "0.16.19"
warp = "0.2"
tokio = "1.8.4"
reqwest = { version = "0.10", features = ["blocking", "json", "rustls"] }

[dev-dependencies.rusqlite]
version = "=0.24.2"
features = ["blob", "serde_json", "i128_blob", "bundled", "trace"]

[[bin]]
name = "stacks-node"
path = "src/main.rs"

[features]
monitoring_prom = ["stacks/monitoring_prom"]
slog_json = ["stacks/slog_json"]
prod-genesis-chainstate = []
default = []
